/* gerado por build.py — edite dados/morros_sul.json, não este arquivo */
window.MORROS_SUL = {
 "metadata": {
  "projeto": "Acima de 300",
  "escopo": "Elevações acima de 300 m nos três estados do Sul, com foco em acampamento",
  "data_revisao": "2026-08-18",
  "estados": [
   "PR",
   "SC",
   "RS"
  ],
  "filtro_minimo_m": 300,
  "aviso": "Altitudes vêm de fontes cartográficas e de montanhismo e variam entre fontes. Informações de acesso e acampamento mudam com frequência: confirme com o parque, a prefeitura ou o proprietário antes de subir.",
  "escala_dificuldade": {
   "1": "Leve",
   "2": "Moderada",
   "3": "Puxada",
   "4": "Difícil",
   "5": "Técnica"
  },
  "campo_acampamento": {
   "cume": "Acampamento no alto, em campo aberto",
   "percurso": "Áreas de acampamento ao longo da trilha",
   "base": "Acampamento na base, sem pernoite no alto",
   "camping": "Camping estruturado, com banheiro e água",
   "proibido": "Pernoite não permitido",
   "verificar": "Sem informação confirmada"
  }
 },
 "morros": [
  {
   "id": "pr-pico-parana",
   "nome": "Pico Paraná",
   "estado": "PR",
   "municipios": [
    "Campina Grande do Sul"
   ],
   "regiao": "Serra do Ibitiraquire",
   "altitude": 1877,
   "lat": -25.2483,
   "lon": -48.8117,
   "tipo": "pico",
   "dificuldade": 5,
   "trilha_km": 8,
   "tempo_h": 7,
   "ganho_m": 1100,
   "acampamento": "percurso",
   "agua": "percurso",
   "acesso": "Estrada de terra até a Fazenda Pico Paraná, em Campina Grande do Sul. Estacionamento pago e vigiado, com banheiro e área de camping na entrada.",
   "epoca": "Abril a setembro, quando o tempo fica mais seco e firme",
   "nota": "O cume mais alto do Sul do Brasil e a subida mais cobiçada do Paraná. A maioria dorme no meio da trilha e ataca o cume de manhã cedo. O trecho final tem correntes e exige cabeça fria.",
   "confianca": "alta"
  },
  {
   "id": "pr-caratuva",
   "nome": "Pico Caratuva",
   "estado": "PR",
   "municipios": [
    "Campina Grande do Sul"
   ],
   "regiao": "Serra do Ibitiraquire",
   "altitude": 1860,
   "lat": -25.2361,
   "lon": -48.8283,
   "tipo": "pico",
   "dificuldade": 4,
   "trilha_km": 6,
   "tempo_h": 5,
   "ganho_m": 950,
   "acampamento": "percurso",
   "agua": "percurso",
   "acesso": "Mesma partida do Pico Paraná, pelas fazendas de Campina Grande do Sul.",
   "epoca": "Abril a setembro",
   "nota": "Segunda montanha mais alta do Sul e vizinha do Pico Paraná. O cume é tomado por caratuva, o bambu anão que dá nome à montanha, e tem antenas de rádio visíveis de longe.",
   "confianca": "alta"
  },
  {
   "id": "sc-boa-vista",
   "nome": "Morro da Boa Vista",
   "estado": "SC",
   "municipios": [
    "Bom Retiro",
    "Urubici"
   ],
   "regiao": "Campo dos Padres",
   "altitude": 1827,
   "lat": -27.9806,
   "lon": -49.4667,
   "tipo": "morro",
   "dificuldade": 3,
   "trilha_km": 12,
   "tempo_h": 5,
   "ganho_m": 500,
   "acampamento": "cume",
   "agua": "percurso",
   "acesso": "Acesso mais usado pela Trilha dos Índios, saindo de Anitápolis. A estrada até o início da trilha está em boas condições e vai de carro de passeio. Parte do percurso cruza propriedades particulares.",
   "epoca": "Outubro a abril para noites menos severas; junho a agosto para geada e chance de neve",
   "nota": "Ponto mais alto de Santa Catarina, medido em 1.823,59 m por um levantamento do IFSC. É um planalto de campo aberto, ótimo para armar barraca, mas o frio no alto é sério e o vento não dá trégua.",
   "confianca": "alta"
  },
  {
   "id": "sc-morro-igreja",
   "nome": "Morro da Igreja",
   "estado": "SC",
   "municipios": [
    "Urubici"
   ],
   "regiao": "Serra Geral",
   "altitude": 1822,
   "lat": -28.1219,
   "lon": -49.4736,
   "tipo": "morro",
   "dificuldade": 1,
   "trilha_km": 1,
   "tempo_h": 1,
   "ganho_m": 40,
   "acampamento": "proibido",
   "agua": "nenhuma",
   "acesso": "Estrada até o alto, a 29 km do centro de Urubici. A visitação tem horário controlado porque o local abriga uma base da Aeronáutica com o radar do CINDACTA II.",
   "epoca": "Junho a agosto para geada e sincelo",
   "nota": "Ponto habitado mais alto do Sul do Brasil e mirante da Pedra Furada. Não dá para dormir aqui, mas serve de base de dia: há campings e pousadas em Urubici.",
   "confianca": "alta"
  },
  {
   "id": "pr-itapiroca",
   "nome": "Pico Itapiroca",
   "estado": "PR",
   "municipios": [
    "Campina Grande do Sul"
   ],
   "regiao": "Serra do Ibitiraquire",
   "altitude": 1805,
   "lat": -25.2556,
   "lon": -48.8156,
   "tipo": "pico",
   "dificuldade": 4,
   "trilha_km": 5,
   "tempo_h": 4,
   "ganho_m": 800,
   "acampamento": "percurso",
   "agua": "percurso",
   "acesso": "Parte da trilha principal do Pico Paraná, pelas fazendas de Campina Grande do Sul.",
   "epoca": "Abril a setembro",
   "nota": "Terceira do estado e a mais curta do circuito dos três cumes. Tem boas áreas de acampamento e vista para Tucum, Camapuã e Ciririca.",
   "confianca": "alta"
  },
  {
   "id": "sc-guizoni",
   "nome": "Morro Bela Vista do Guizoni",
   "estado": "SC",
   "municipios": [
    "Bom Retiro"
   ],
   "regiao": "Campo dos Padres",
   "altitude": 1804,
   "lat": -27.9917,
   "lon": -49.4722,
   "tipo": "morro",
   "dificuldade": 3,
   "trilha_km": 10,
   "tempo_h": 4,
   "ganho_m": 450,
   "acampamento": "cume",
   "agua": "percurso",
   "acesso": "Mesma região do Morro da Boa Vista, por estradas rurais de Bom Retiro.",
   "epoca": "Outubro a abril",
   "nota": "Terceiro ponto mais alto do estado e quase sempre vazio. Campo limpo no topo e horizonte aberto para o Campo dos Padres.",
   "confianca": "media"
  },
  {
   "id": "sc-morro-preto",
   "nome": "Morro Preto",
   "estado": "SC",
   "municipios": [
    "Urubici"
   ],
   "regiao": "Serra Geral",
   "altitude": 1799,
   "lat": -28.1028,
   "lon": -49.4611,
   "tipo": "morro",
   "dificuldade": 2,
   "trilha_km": 6,
   "tempo_h": 3,
   "ganho_m": 300,
   "acampamento": "verificar",
   "agua": "sazonal",
   "acesso": "Fica a 2,9 km do Morro da Igreja, por campo aberto e estradas de fazenda.",
   "epoca": "Outubro a abril",
   "nota": "Ficou fora das listas oficiais por muito tempo e por isso quase não recebe visita. Terreno particular: peça autorização na propriedade.",
   "confianca": "media"
  },
  {
   "id": "sc-convento-padres",
   "nome": "Morro Convento dos Padres",
   "estado": "SC",
   "municipios": [
    "Bom Retiro"
   ],
   "regiao": "Campo dos Padres",
   "altitude": 1790,
   "lat": -27.9694,
   "lon": -49.4889,
   "tipo": "morro",
   "dificuldade": 3,
   "trilha_km": 11,
   "tempo_h": 4,
   "ganho_m": 420,
   "acampamento": "cume",
   "agua": "percurso",
   "acesso": "Estradas rurais de Bom Retiro, mesma região do Campo dos Padres.",
   "epoca": "Outubro a abril",
   "nota": "Grande planalto a cerca de 1.790 m, com pastagem e araucárias esparsas. Espaço de sobra para barraca, desde que o proprietário libere.",
   "confianca": "media"
  },
  {
   "id": "pr-ciririca",
   "nome": "Pico Ciririca",
   "estado": "PR",
   "municipios": [
    "Antonina"
   ],
   "regiao": "Serra do Ibitiraquire",
   "altitude": 1760,
   "lat": -25.2833,
   "lon": -48.8028,
   "tipo": "pico",
   "dificuldade": 5,
   "trilha_km": 9,
   "tempo_h": 8,
   "ganho_m": 1200,
   "acampamento": "percurso",
   "agua": "percurso",
   "acesso": "Acesso longo pela Serra do Ibitiraquire. Vá com guia: a rota tem trechos expostos e é fácil se perder.",
   "epoca": "Abril a setembro",
   "nota": "Fama de ser a montanha mais dura do Paraná. Placas de rocha lisa no trecho final e pouca gente na trilha mesmo em feriado.",
   "confianca": "media"
  },
  {
   "id": "pr-ferraria",
   "nome": "Pico Ferraria",
   "estado": "PR",
   "municipios": [
    "Campina Grande do Sul"
   ],
   "regiao": "Serra do Ibitiraquire",
   "altitude": 1745,
   "lat": -25.2194,
   "lon": -48.8333,
   "tipo": "pico",
   "dificuldade": 5,
   "trilha_km": 8,
   "tempo_h": 7,
   "ganho_m": 1000,
   "acampamento": "percurso",
   "agua": "percurso",
   "acesso": "A rota clássica pela Picada do Cristóvão está fechada. O acesso atual sai da Fazenda Pico Paraná e contorna as encostas do Caratuva.",
   "epoca": "Abril a setembro",
   "nota": "Confirme o acesso antes de ir: as autorizações de passagem por aqui mudam de tempos em tempos.",
   "confianca": "media"
  },
  {
   "id": "pr-tucum",
   "nome": "Pico Tucum",
   "estado": "PR",
   "municipios": [
    "Antonina",
    "Campina Grande do Sul"
   ],
   "regiao": "Serra do Ibitiraquire",
   "altitude": 1720,
   "lat": -25.2917,
   "lon": -48.8222,
   "tipo": "pico",
   "dificuldade": 4,
   "trilha_km": 7,
   "tempo_h": 6,
   "ganho_m": 950,
   "acampamento": "percurso",
   "agua": "percurso",
   "acesso": "Trilha convencional passa pelo Camacuã e atravessa o topo descampado do Camapuã.",
   "epoca": "Abril a setembro",
   "nota": "Pouco visitado para o tamanho da vista. Um dos melhores lugares da Serra do Mar para ver o nascer do sol sem fila.",
   "confianca": "media"
  },
  {
   "id": "pr-capivari-grande",
   "nome": "Morro Capivari Grande",
   "estado": "PR",
   "municipios": [
    "Campina Grande do Sul"
   ],
   "regiao": "Serra do Capivari Grande",
   "altitude": 1676,
   "lat": -25.1528,
   "lon": -48.8556,
   "tipo": "morro",
   "dificuldade": 4,
   "trilha_km": 7,
   "tempo_h": 6,
   "ganho_m": 900,
   "acampamento": "verificar",
   "agua": "sazonal",
   "acesso": "Bloco isolado ao norte do Ibitiraquire. Acesso por estradas rurais e propriedades particulares.",
   "epoca": "Abril a setembro",
   "nota": "Conjunto pouco frequentado, com cumes entre 1.640 e 1.676 m. Confirme a passagem com os proprietários antes de subir.",
   "confianca": "media"
  },
  {
   "id": "sc-quiriri",
   "nome": "Serra do Quiriri",
   "estado": "SC",
   "municipios": [
    "Campo Alegre",
    "Garuva"
   ],
   "regiao": "Serra do Mar catarinense",
   "altitude": 1580,
   "lat": -26.1,
   "lon": -49.1667,
   "tipo": "serra",
   "dificuldade": 3,
   "trilha_km": 8,
   "tempo_h": 4,
   "ganho_m": 500,
   "acampamento": "cume",
   "agua": "percurso",
   "acesso": "Estrada de terra a partir de Campo Alegre, no norte do estado.",
   "epoca": "Março a novembro",
   "nota": "Conjunto com cerca de 30 cumes entre 1.300 e 1.580 m. Do alto dá para ver Joinville e o mar em dia limpo. Campos de altitude com bons pontos para barraca.",
   "confianca": "media"
  },
  {
   "id": "pr-morro-leao",
   "nome": "Morro do Leão",
   "estado": "PR",
   "municipios": [
    "Piraquara"
   ],
   "regiao": "Serra do Leão",
   "altitude": 1564,
   "lat": -25.4472,
   "lon": -48.8833,
   "tipo": "morro",
   "dificuldade": 4,
   "trilha_km": 6,
   "tempo_h": 5,
   "ganho_m": 800,
   "acampamento": "verificar",
   "agua": "sazonal",
   "acesso": "Acesso por estrada de terra a partir de Piraquara, em área de mananciais com restrição de entrada.",
   "epoca": "Abril a setembro",
   "nota": "Ponto culminante da Serra do Leão, entre a Graciosa e o Marumbi. Área de proteção de mananciais: confirme se a visitação está liberada.",
   "confianca": "media"
  },
  {
   "id": "pr-olimpo-marumbi",
   "nome": "Pico Olimpo",
   "estado": "PR",
   "municipios": [
    "Morretes"
   ],
   "regiao": "Conjunto Marumbi",
   "altitude": 1539,
   "lat": -25.4394,
   "lon": -48.9203,
   "tipo": "pico",
   "dificuldade": 4,
   "trilha_km": 5,
   "tempo_h": 4,
   "ganho_m": 1050,
   "acampamento": "camping",
   "agua": "base",
   "acesso": "Parque Estadual Pico do Marumbi. Chega-se de trem pela Estrada de Ferro Curitiba–Paranaguá ou por estrada de terra até a Estação Marumbi.",
   "epoca": "O ano todo, evitando dias de chuva na rocha",
   "nota": "Cume mais alto do Conjunto Marumbi. O camping fica na sede do parque, na base, e o ataque ao cume é feito no dia. Registre a entrada e a saída na portaria.",
   "confianca": "alta"
  },
  {
   "id": "sc-corvo-branco",
   "nome": "Morro do Corvo Branco",
   "estado": "SC",
   "municipios": [
    "Urubici",
    "Grão-Pará"
   ],
   "regiao": "Serra Geral",
   "altitude": 1460,
   "lat": -28.13,
   "lon": -49.3417,
   "tipo": "morro",
   "dificuldade": 2,
   "trilha_km": 4,
   "tempo_h": 2,
   "ganho_m": 250,
   "acampamento": "base",
   "agua": "base",
   "acesso": "Pela Serra do Corvo Branco, estrada de terra com paredões cortados na rocha. Trecho fecha em dias de chuva forte.",
   "epoca": "Março a novembro",
   "nota": "O corte da serra é uma das paisagens mais fotografadas de SC. Há campings e áreas de pernoite na base, do lado de Urubici.",
   "confianca": "media"
  },
  {
   "id": "pr-mae-catira",
   "nome": "Mãe Catira",
   "estado": "PR",
   "municipios": [
    "Quatro Barras"
   ],
   "regiao": "Serra da Graciosa",
   "altitude": 1453,
   "lat": -25.3222,
   "lon": -48.8944,
   "tipo": "morro",
   "dificuldade": 3,
   "trilha_km": 5,
   "tempo_h": 4,
   "ganho_m": 600,
   "acampamento": "verificar",
   "agua": "sazonal",
   "acesso": "Partida próxima à Estrada da Graciosa, em Quatro Barras.",
   "epoca": "O ano todo",
   "nota": "Bloco da Serra da Graciosa, na mesma faixa do Alto da Graciosa. Boa opção de fim de semana curto saindo de Curitiba.",
   "confianca": "media"
  },
  {
   "id": "pr-anhangava",
   "nome": "Morro Anhangava",
   "estado": "PR",
   "municipios": [
    "Quatro Barras"
   ],
   "regiao": "Serra da Baitaca",
   "altitude": 1420,
   "lat": -25.3897,
   "lon": -48.9861,
   "tipo": "morro",
   "dificuldade": 2,
   "trilha_km": 3,
   "tempo_h": 2,
   "ganho_m": 500,
   "acampamento": "cume",
   "agua": "nenhuma",
   "acesso": "Estrada asfaltada até a base, em Quatro Barras, a menos de uma hora de Curitiba.",
   "epoca": "O ano todo",
   "nota": "A montanha mais acessível do Paraná e escola de escalada da região. Cume de rocha limpa com vista para Curitiba. Suba com toda a água do dia: não há fonte no caminho.",
   "confianca": "alta"
  },
  {
   "id": "sc-rio-do-rastro",
   "nome": "Mirante da Serra do Rio do Rastro",
   "estado": "SC",
   "municipios": [
    "Bom Jardim da Serra"
   ],
   "regiao": "Serra Geral",
   "altitude": 1420,
   "lat": -28.3897,
   "lon": -49.5411,
   "tipo": "mirante",
   "dificuldade": 1,
   "trilha_km": 1,
   "tempo_h": 1,
   "ganho_m": 30,
   "acampamento": "base",
   "agua": "base",
   "acesso": "Pela SC-390, asfaltada, com estacionamento no alto. Entrada gratuita.",
   "epoca": "O ano todo, com mais chance de céu limpo no inverno",
   "nota": "O mirante fica no topo da serra, com 1.200 m de desnível até a planície. Não é ponto de acampamento, mas os campings de Bom Jardim da Serra ficam a poucos quilômetros.",
   "confianca": "alta"
  },
  {
   "id": "rs-monte-negro",
   "nome": "Pico do Monte Negro",
   "estado": "RS",
   "municipios": [
    "São José dos Ausentes"
   ],
   "regiao": "Campos de Cima da Serra",
   "altitude": 1403,
   "lat": -28.6167,
   "lon": -49.8,
   "tipo": "pico",
   "dificuldade": 2,
   "trilha_km": 3,
   "tempo_h": 2,
   "ganho_m": 200,
   "acampamento": "base",
   "agua": "base",
   "acesso": "Estrada municipal Silveira, de saibro e chão batido, a 45 km do centro de São José dos Ausentes. Dá para chegar de carro até o estacionamento na base; o caminho passa dentro de uma fazenda.",
   "epoca": "O ano todo. Suba de manhã para escapar da viração, a nuvem espessa que sobe do litoral e fecha o cânion",
   "nota": "Ponto mais alto e mais frio do Rio Grande do Sul, na borda do Cânion Monte Negro, que tem 700 m de profundidade. A subida final é íngreme e ventosa. As pousadas-fazenda da região recebem barraca.",
   "confianca": "alta"
  },
  {
   "id": "pr-morro-canal",
   "nome": "Morro do Canal",
   "estado": "PR",
   "municipios": [
    "Piraquara"
   ],
   "regiao": "Serra da Baitaca",
   "altitude": 1400,
   "lat": -25.4667,
   "lon": -48.9333,
   "tipo": "morro",
   "dificuldade": 3,
   "trilha_km": 6,
   "tempo_h": 4,
   "ganho_m": 600,
   "acampamento": "verificar",
   "agua": "percurso",
   "acesso": "Partida pela região do Mananciais da Serra, em Piraquara, com controle de entrada.",
   "epoca": "O ano todo",
   "nota": "Trilha em mata fechada até um cume aberto sobre o vale. A entrada depende de autorização da área de mananciais.",
   "confianca": "media"
  },
  {
   "id": "rs-fortaleza",
   "nome": "Borda do Cânion Fortaleza",
   "estado": "RS",
   "municipios": [
    "Cambará do Sul",
    "Jacinto Machado"
   ],
   "regiao": "Aparados da Serra",
   "altitude": 1150,
   "lat": -29.0722,
   "lon": -50.0361,
   "tipo": "canion",
   "dificuldade": 2,
   "trilha_km": 5,
   "tempo_h": 3,
   "ganho_m": 120,
   "acampamento": "proibido",
   "agua": "base",
   "acesso": "Parque Nacional da Serra Geral, com entrada por Cambará do Sul. Ingresso e horário definidos pelo ICMBio.",
   "epoca": "Abril a setembro, quando o céu abre mais cedo",
   "nota": "Paredão de 900 m sobre a planície litorânea. Acampar dentro do parque não é permitido: os campings ficam na estrada de Cambará do Sul.",
   "confianca": "media"
  },
  {
   "id": "sc-cambirela",
   "nome": "Morro do Cambirela",
   "estado": "SC",
   "municipios": [
    "Palhoça"
   ],
   "regiao": "Serra do Tabuleiro",
   "altitude": 1043,
   "lat": -27.6853,
   "lon": -48.6753,
   "tipo": "morro",
   "dificuldade": 4,
   "trilha_km": 7,
   "tempo_h": 5,
   "ganho_m": 1000,
   "acampamento": "cume",
   "agua": "percurso",
   "acesso": "Partida em Palhoça, na Grande Florianópolis. Trilha dentro do Parque Estadual da Serra do Tabuleiro.",
   "epoca": "Março a novembro",
   "nota": "Subida direta do nível do mar até mil metros, sem alívio. O cume tem lajes de granito com vista para a baía e para a ilha de Florianópolis. Confirme as regras de pernoite com a administração do parque.",
   "confianca": "media"
  },
  {
   "id": "sc-pedra-branca",
   "nome": "Pedra Branca",
   "estado": "SC",
   "municipios": [
    "Palhoça"
   ],
   "regiao": "Serra do Tabuleiro",
   "altitude": 1000,
   "lat": -27.7,
   "lon": -48.69,
   "tipo": "pedra",
   "dificuldade": 4,
   "trilha_km": 8,
   "tempo_h": 5,
   "ganho_m": 950,
   "acampamento": "verificar",
   "agua": "percurso",
   "acesso": "Mesma região do Cambirela, com trilhas que saem de Palhoça.",
   "epoca": "Março a novembro",
   "nota": "Domo de granito claro visível de boa parte da Grande Florianópolis. Trilha menos marcada que a do Cambirela.",
   "confianca": "media"
  },
  {
   "id": "rs-morro-sete-lagoas",
   "nome": "Morro das Sete Lagoas",
   "estado": "RS",
   "municipios": [
    "Barão do Triunfo"
   ],
   "regiao": "Escudo Sul-rio-grandense",
   "altitude": 875,
   "lat": -30.4,
   "lon": -51.7,
   "tipo": "morro",
   "dificuldade": 3,
   "trilha_km": 6,
   "tempo_h": 3,
   "ganho_m": 450,
   "acampamento": "verificar",
   "agua": "sazonal",
   "acesso": "Estradas rurais na localidade de Morrinhos, em Barão do Triunfo.",
   "epoca": "Março a novembro",
   "nota": "Um dos pontos mais altos fora da Serra Geral no RS. Região de campo e mata, com acesso por propriedades particulares.",
   "confianca": "media"
  },
  {
   "id": "rs-morro-grande-rolante",
   "nome": "Morro Grande",
   "estado": "RS",
   "municipios": [
    "Rolante"
   ],
   "regiao": "Encosta da Serra Geral",
   "altitude": 841,
   "lat": -29.5886,
   "lon": -50.5278,
   "tipo": "morro",
   "dificuldade": 4,
   "trilha_km": 12,
   "tempo_h": 5,
   "ganho_m": 770,
   "acampamento": "cume",
   "agua": "sazonal",
   "acesso": "Subida pela face oeste a partir da área de pouso de voo livre, a 62 m de altitude. São 12 km de percurso.",
   "epoca": "Março a novembro",
   "nota": "Rampa de voo livre com vista para o vale do Rolante. O desnível de 770 m faz dela uma das subidas mais longas do estado.",
   "confianca": "alta"
  },
  {
   "id": "rs-cantagalo",
   "nome": "Morro Cantagalo",
   "estado": "RS",
   "municipios": [
    "Rolante"
   ],
   "regiao": "Encosta da Serra Geral",
   "altitude": 829,
   "lat": -29.52,
   "lon": -50.55,
   "tipo": "morro",
   "dificuldade": 3,
   "trilha_km": 8,
   "tempo_h": 4,
   "ganho_m": 600,
   "acampamento": "verificar",
   "agua": "sazonal",
   "acesso": "Estradas rurais de Rolante, na encosta da serra.",
   "epoca": "Março a novembro",
   "nota": "Vizinho do Morro Grande, com perfil parecido e menos gente. Terreno particular na maior parte do trajeto.",
   "confianca": "media"
  },
  {
   "id": "sc-morro-bau",
   "nome": "Morro do Baú",
   "estado": "SC",
   "municipios": [
    "Ilhota"
   ],
   "regiao": "Vale do Itajaí",
   "altitude": 819,
   "lat": -26.8236,
   "lon": -48.9425,
   "tipo": "morro",
   "dificuldade": 2,
   "trilha_km": 3,
   "tempo_h": 2,
   "ganho_m": 450,
   "acampamento": "base",
   "agua": "base",
   "acesso": "Estrada até a Reserva Biológica Morro do Baú, em Ilhota, entre Blumenau e Itajaí.",
   "epoca": "O ano todo",
   "nota": "Rocha em forma de baú visível do vale inteiro. Área de reserva com regras próprias de visitação: pernoite só nas áreas autorizadas na base.",
   "confianca": "media"
  },
  {
   "id": "rs-serra-do-pinto",
   "nome": "Serra do Pinto",
   "estado": "RS",
   "municipios": [
    "Itati"
   ],
   "regiao": "Rota do Sol",
   "altitude": 803,
   "lat": -29.3544,
   "lon": -50.1722,
   "tipo": "serra",
   "dificuldade": 3,
   "trilha_km": 11,
   "tempo_h": 4,
   "ganho_m": 670,
   "acampamento": "base",
   "agua": "base",
   "acesso": "Subida pela RS-486, a Rota do Sol, a partir de Santana (137 m) até o topo da serra.",
   "epoca": "Março a novembro",
   "nota": "Ganho de 670 m ao longo da estrada, com mirante no alto. Bom trajeto para quem quer altitude sem trilha técnica.",
   "confianca": "alta"
  },
  {
   "id": "rs-ferrabraz",
   "nome": "Morro Ferrabraz",
   "estado": "RS",
   "municipios": [
    "Sapiranga"
   ],
   "regiao": "Encosta da Serra Geral",
   "altitude": 779,
   "lat": -29.6042,
   "lon": -50.9686,
   "tipo": "morro",
   "dificuldade": 2,
   "trilha_km": 4.2,
   "tempo_h": 2,
   "ganho_m": 510,
   "acampamento": "base",
   "agua": "base",
   "acesso": "Da pista de pouso na estrada do Carlão até a rampa sudeste, 4,2 km de percurso.",
   "epoca": "O ano todo",
   "nota": "Um dos pontos de voo livre mais conhecidos do estado, a uma hora de Porto Alegre. Estrutura de apoio na rampa e campings na base.",
   "confianca": "alta"
  },
  {
   "id": "rs-canastra",
   "nome": "Morro da Canastra",
   "estado": "RS",
   "municipios": [
    "Riozinho"
   ],
   "regiao": "Encosta da Serra Geral",
   "altitude": 750,
   "lat": -29.62,
   "lon": -50.45,
   "tipo": "morro",
   "dificuldade": 3,
   "trilha_km": 7,
   "tempo_h": 3,
   "ganho_m": 550,
   "acampamento": "verificar",
   "agua": "sazonal",
   "acesso": "Estradas rurais de Riozinho, no Vale do Paranhana.",
   "epoca": "Março a novembro",
   "nota": "Região de cachoeiras e mata atlântica preservada. Combine com o Morro da Pirâmide, a poucos quilômetros.",
   "confianca": "media"
  },
  {
   "id": "rs-piramide",
   "nome": "Morro da Pirâmide",
   "estado": "RS",
   "municipios": [
    "Riozinho"
   ],
   "regiao": "Encosta da Serra Geral",
   "altitude": 680,
   "lat": -29.63,
   "lon": -50.44,
   "tipo": "morro",
   "dificuldade": 3,
   "trilha_km": 6,
   "tempo_h": 3,
   "ganho_m": 480,
   "acampamento": "verificar",
   "agua": "sazonal",
   "acesso": "Acesso por Riozinho, no Vale do Paranhana.",
   "epoca": "Março a novembro",
   "nota": "Silhueta triangular que dá nome ao morro. Pouca informação de trilha disponível: vá com quem conhece.",
   "confianca": "media"
  },
  {
   "id": "rs-morro-agudo-caraa",
   "nome": "Morro Agudo",
   "estado": "RS",
   "municipios": [
    "Caraá"
   ],
   "regiao": "Encosta da Serra Geral",
   "altitude": 655,
   "lat": -29.78,
   "lon": -50.43,
   "tipo": "morro",
   "dificuldade": 3,
   "trilha_km": 5,
   "tempo_h": 3,
   "ganho_m": 450,
   "acampamento": "verificar",
   "agua": "sazonal",
   "acesso": "Estradas rurais de Caraá, entre Osório e Santo Antônio da Patrulha.",
   "epoca": "Março a novembro",
   "nota": "O mais alto entre os vários Morros Agudo do estado. Cume cônico com vista para a planície litorânea.",
   "confianca": "media"
  },
  {
   "id": "rs-morro-diabo",
   "nome": "Morro do Diabo",
   "estado": "RS",
   "municipios": [
    "Caxias do Sul"
   ],
   "regiao": "Serra Gaúcha",
   "altitude": 650,
   "lat": -29.3402,
   "lon": -51.3854,
   "tipo": "morro",
   "dificuldade": 2,
   "trilha_km": 4,
   "tempo_h": 2,
   "ganho_m": 300,
   "acampamento": "verificar",
   "agua": "nenhuma",
   "acesso": "Acesso por estradas vicinais de Caxias do Sul.",
   "epoca": "O ano todo",
   "nota": "Rampa usada por pilotos de parapente, com vista aberta para as planícies abaixo. Marco visual da região.",
   "confianca": "media"
  },
  {
   "id": "rs-cerro-partido",
   "nome": "Cerro Partido",
   "estado": "RS",
   "municipios": [
    "São Jerônimo"
   ],
   "regiao": "Escudo Sul-rio-grandense",
   "altitude": 590,
   "lat": -30.0,
   "lon": -51.75,
   "tipo": "cerro",
   "dificuldade": 2,
   "trilha_km": 5,
   "tempo_h": 2,
   "ganho_m": 350,
   "acampamento": "verificar",
   "agua": "sazonal",
   "acesso": "Estradas rurais de São Jerônimo, na região carbonífera.",
   "epoca": "Março a novembro",
   "nota": "Campo aberto e afloramentos de granito. Região pouco explorada por trilheiros, com muitos cerros acima de 500 m.",
   "confianca": "media"
  },
  {
   "id": "rs-lohmann",
   "nome": "Morro Lohmann",
   "estado": "RS",
   "municipios": [
    "Roca Sales"
   ],
   "regiao": "Vale do Taquari",
   "altitude": 580,
   "lat": -29.28,
   "lon": -51.87,
   "tipo": "morro",
   "dificuldade": 2,
   "trilha_km": 5,
   "tempo_h": 2,
   "ganho_m": 380,
   "acampamento": "verificar",
   "agua": "sazonal",
   "acesso": "Estradas rurais de Roca Sales.",
   "epoca": "Março a novembro",
   "nota": "Ponto alto do Vale do Taquari, com vista para o rio e para as colônias alemãs da região.",
   "confianca": "media"
  },
  {
   "id": "rs-cerro-branco",
   "nome": "Cerro Branco",
   "estado": "RS",
   "municipios": [
    "Cerro Branco"
   ],
   "regiao": "Depressão Central",
   "altitude": 573,
   "lat": -29.66,
   "lon": -52.9,
   "tipo": "cerro",
   "dificuldade": 2,
   "trilha_km": 4,
   "tempo_h": 2,
   "ganho_m": 300,
   "acampamento": "verificar",
   "agua": "sazonal",
   "acesso": "Estradas rurais no município de mesmo nome, perto de Candelária.",
   "epoca": "Março a novembro",
   "nota": "Fica de frente para o Botucaraí, na mesma faixa de altitude. Dá para encaixar os dois no mesmo fim de semana.",
   "confianca": "media"
  },
  {
   "id": "rs-botucarai",
   "nome": "Cerro do Botucaraí",
   "estado": "RS",
   "municipios": [
    "Candelária"
   ],
   "regiao": "Depressão Central",
   "altitude": 569,
   "lat": -29.63,
   "lon": -52.72,
   "tipo": "cerro",
   "dificuldade": 3,
   "trilha_km": 1.2,
   "tempo_h": 2,
   "ganho_m": 350,
   "acampamento": "base",
   "agua": "nenhuma",
   "acesso": "Estrada de chão batido em boas condições, a 8 km do centro de Candelária, pela RSC-287. Estacione na clareira da capela, onde começa a trilha.",
   "epoca": "Tempo seco. Depois de chuva forte a subida fica escorregadia e perigosa",
   "nota": "O morro isolado mais alto do estado, com 569,63 m. Só 1,2 km de trilha, mas íngreme o suficiente para exigir joelhos e fôlego. Leve pelo menos dois litros de água: não há fonte no caminho.",
   "confianca": "alta"
  },
  {
   "id": "rs-morro-gaucho",
   "nome": "Morro Gaúcho",
   "estado": "RS",
   "municipios": [
    "Arroio do Meio"
   ],
   "regiao": "Vale do Taquari",
   "altitude": 550,
   "lat": -29.35,
   "lon": -51.95,
   "tipo": "morro",
   "dificuldade": 2,
   "trilha_km": 4,
   "tempo_h": 2,
   "ganho_m": 400,
   "acampamento": "base",
   "agua": "base",
   "acesso": "Acesso sinalizado a partir de Arroio do Meio, no Vale do Taquari.",
   "epoca": "O ano todo",
   "nota": "Mirante conhecido do vale, com rampa de voo livre e estrutura de apoio na base.",
   "confianca": "media"
  },
  {
   "id": "sc-morro-lagoa",
   "nome": "Morro da Lagoa da Conceição",
   "estado": "SC",
   "municipios": [
    "Florianópolis"
   ],
   "regiao": "Ilha de Santa Catarina",
   "altitude": 493,
   "lat": -27.5966,
   "lon": -48.4736,
   "tipo": "morro",
   "dificuldade": 2,
   "trilha_km": 4,
   "tempo_h": 2,
   "ganho_m": 400,
   "acampamento": "proibido",
   "agua": "nenhuma",
   "acesso": "Trilhas saindo do Córrego Grande e da Lagoa da Conceição, dentro do Parque Natural Municipal do Maciço da Costeira.",
   "epoca": "O ano todo",
   "nota": "Melhor pôr do sol urbano da ilha, com a lagoa de um lado e a baía do outro. Área de parque municipal: acampar não é permitido.",
   "confianca": "media"
  },
  {
   "id": "rs-borussia",
   "nome": "Morro da Borússia",
   "estado": "RS",
   "municipios": [
    "Osório"
   ],
   "regiao": "Litoral Norte",
   "altitude": 398,
   "lat": -29.8542,
   "lon": -50.3236,
   "tipo": "morro",
   "dificuldade": 2,
   "trilha_km": 5,
   "tempo_h": 2,
   "ganho_m": 350,
   "acampamento": "base",
   "agua": "base",
   "acesso": "Estrada do Morro da Borússia, saindo de Osório em direção à serra.",
   "epoca": "O ano todo",
   "nota": "Estrada cênica com cascatas e pousadas ao longo do caminho. Do alto dá para ver as lagoas do litoral norte e o parque eólico.",
   "confianca": "alta"
  },
  {
   "id": "rs-serra-erval",
   "nome": "Serra do Erval",
   "estado": "RS",
   "municipios": [
    "Barão do Triunfo"
   ],
   "regiao": "Escudo Sul-rio-grandense",
   "altitude": 390,
   "lat": -30.38,
   "lon": -51.72,
   "tipo": "serra",
   "dificuldade": 2,
   "trilha_km": 6,
   "tempo_h": 3,
   "ganho_m": 280,
   "acampamento": "verificar",
   "agua": "sazonal",
   "acesso": "Estradas rurais de Barão do Triunfo.",
   "epoca": "Março a novembro",
   "nota": "Campos de cima do escudo, com afloramentos e mata ciliar. Área rural: combine a passagem com os moradores.",
   "confianca": "media"
  },
  {
   "id": "rs-morro-pelado-osorio",
   "nome": "Morro Pelado",
   "estado": "RS",
   "municipios": [
    "Osório"
   ],
   "regiao": "Litoral Norte",
   "altitude": 343,
   "lat": -29.87,
   "lon": -50.36,
   "tipo": "morro",
   "dificuldade": 2,
   "trilha_km": 5,
   "tempo_h": 2,
   "ganho_m": 270,
   "acampamento": "verificar",
   "agua": "sazonal",
   "acesso": "Estradas de terra na zona rural de Osório, perto do Morro da Borússia.",
   "epoca": "O ano todo",
   "nota": "Cume sem vegetação alta, formado em basalto, com vista de 360 graus sobre os vales e as cidades vizinhas. Bom lugar para pôr do sol.",
   "confianca": "media"
  },
  {
   "id": "rs-serra-lanceiros",
   "nome": "Serra dos Lanceiros",
   "estado": "RS",
   "municipios": [
    "Caçapava do Sul"
   ],
   "regiao": "Escudo Sul-rio-grandense",
   "altitude": 339,
   "lat": -30.52,
   "lon": -53.49,
   "tipo": "serra",
   "dificuldade": 2,
   "trilha_km": 5,
   "tempo_h": 2,
   "ganho_m": 200,
   "acampamento": "verificar",
   "agua": "sazonal",
   "acesso": "Estradas rurais de Caçapava do Sul, na mesma região da Pedra do Segredo.",
   "epoca": "O ano todo",
   "nota": "Nome ligado ao combate dos Porongos, na Farroupilha. Campo aberto, com pedra à mostra e horizonte largo.",
   "confianca": "media"
  },
  {
   "id": "rs-itacolomi",
   "nome": "Morro Itacolomi",
   "estado": "RS",
   "municipios": [
    "Gravataí"
   ],
   "regiao": "Região Metropolitana",
   "altitude": 335,
   "lat": -29.92,
   "lon": -50.87,
   "tipo": "morro",
   "dificuldade": 2,
   "trilha_km": 4,
   "tempo_h": 2,
   "ganho_m": 260,
   "acampamento": "verificar",
   "agua": "nenhuma",
   "acesso": "Zona rural de Gravataí, a menos de uma hora de Porto Alegre.",
   "epoca": "O ano todo",
   "nota": "Silhueta reconhecível de quem passa pela BR-290. Opção de trilha curta perto da capital.",
   "confianca": "media"
  },
  {
   "id": "rs-pedra-segredo",
   "nome": "Pedra do Segredo",
   "estado": "RS",
   "municipios": [
    "Caçapava do Sul"
   ],
   "regiao": "Escudo Sul-rio-grandense",
   "altitude": 325,
   "lat": -30.5717,
   "lon": -53.4392,
   "tipo": "pedra",
   "dificuldade": 2,
   "trilha_km": 3.5,
   "tempo_h": 2,
   "ganho_m": 160,
   "acampamento": "camping",
   "agua": "base",
   "acesso": "A cerca de 280 km de Porto Alegre, por Caçapava do Sul. Acesso sinalizado, com área de visitação organizada.",
   "epoca": "O ano todo",
   "nota": "Bloco de granito equilibrado sobre uma base estreita, cercado de cavernas e outras formações. Tem camping estruturado no local e as Guaritas do Camaquã ficam perto.",
   "confianca": "alta"
  },
  {
   "id": "rs-morro-santana",
   "nome": "Morro Santana",
   "estado": "RS",
   "municipios": [
    "Porto Alegre"
   ],
   "regiao": "Região Metropolitana",
   "altitude": 310,
   "lat": -30.0553,
   "lon": -51.1236,
   "tipo": "morro",
   "dificuldade": 2,
   "trilha_km": 6,
   "tempo_h": 3,
   "ganho_m": 250,
   "acampamento": "proibido",
   "agua": "nenhuma",
   "acesso": "Trilhas partindo do campus do Vale da UFRGS e da zona leste de Porto Alegre.",
   "epoca": "O ano todo",
   "nota": "Ponto mais alto de Porto Alegre, com campo nativo e mata preservada. Área institucional da UFRGS: visitação de dia, sem pernoite.",
   "confianca": "alta"
  }
 ]
 [
  {
    "id": "sc-santo-anjo",
    "nome": "Morro do Santo Anjo",
    "estado": "SC",
    "municipios": ["Massaranduba"],
    "regiao": "Vale do Itapocu",
    "altitude": 830,
    "lat": -26.5583,
    "lon": -49.0472,
    "tipo": "morro",
    "dificuldade": 1,
    "trilha_km": 0.8,
    "tempo_h": 0.5,
    "ganho_m": 120,
    "acampamento": "cume",
    "agua": "nenhuma",
    "acesso": "Localidade Alto Guarani, a cerca de 15 km do centro de Massaranduba. Acesso gratuito e aberto o ano todo. A estrada é de paralelepípedo no trecho mais sinuoso: carro de passeio chega, mas exige mão firme nas curvas. Do estacionamento até o alto são uns 20 minutos de subida curta e íngreme, dá para subir com a mochila cargueira nas costas.",
    "epoca": "O ano todo",
    "nota": "Um dos morros mais campados do norte de SC, e por bons motivos: vista de 360 graus, capela no ponto mais alto, e o alinhamento com Barra Velha faz com que dê para ver o nascer e o pôr do sol no mesmo lugar. Não há água nenhuma no alto: suba com tudo o que vai beber e cozinhar. O tempo vira rápido ali, mesmo em dia limpo na chegada.",
    "confianca": "media"
  },
  {
    "id": "sc-monte-crista",
    "nome": "Monte Crista",
    "estado": "SC",
    "municipios": ["Garuva"],
    "regiao": "Serra do Mar catarinense",
    "altitude": 927,
    "lat": -26.0583,
    "lon": -48.9083,
    "tipo": "morro",
    "dificuldade": 3,
    "trilha_km": 9,
    "tempo_h": 5,
    "ganho_m": 850,
    "acampamento": "cume",
    "agua": "percurso",
    "acesso": "Saída da BR-101 em Garuva por estrada de terra sinalizada com um monumento de concreto, mais uns 2 km entre bananais até o estacionamento, dentro de propriedade particular. Cobra-se entrada por veículo e por pessoa. Há banheiro e um bar pequeno na recepção. A trilha começa numa ponte pênsil sobre o Rio Três Barras.",
    "epoca": "Março a novembro",
    "nota": "A montanha mais procurada da região de Joinville. A subida é pelo Caminho dos Ambrósios, remanescente do Peabiru, com trechos de escadaria de pedra ainda em pé. Não é técnica: é resistência, subida íngreme e constante. Atenção ao ponto de acampar: o melhor lugar não é o cume, é um marco um pouco abaixo, protegido do vento. Quem arma no topo passa a noite levando pancada. A temperatura despenca depois do escurecer, leve saco de dormir de verdade. Há pontos de água na trilha, incluindo cachoeiras.",
    "confianca": "media"
  }
]
};
